spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.error.include-message=always
server.error.include-stacktrace=always

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.tryItOutEnabled=true
