spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.error.include-message=never
server.error.include-stacktrace=never

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

spring.web.resources.add-mappings=false

server.compression.enabled=true
server.compression.mime-types=application/json,text/plain,text/html,text/xml,application/javascript,text/css
server.forward-headers-strategy=native

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
